name: Release Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (use Semver Semantics)'
        required: true
    branches:
      - main

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Edit Toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "pyproject.toml"
          key: "tool.poetry.version"
          value: "${{ github.event.inputs.version }}"
      - name: Update the changelog
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -a -m "[automated:release] Release ${{ github.event.inputs.version }}"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CI_PAT }}
          title: '[automated:release] Release ${{ github.event.inputs.version }}'
          branch: release
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.CI_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
