
name: Common Spot Verification Workflow

on:
  schedule:
    - cron: '23 6 * * 0'
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  call-verification-workflow:
    uses: spotinst/devops-scripts/.github/workflows/common-verification-workflow.yml@master
    secrets: inherit
