
name: Publish package to PyPI

on:
    push:
        branches:
        - main
    release:
        types:
        - created

jobs:   
    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/ocean-spark-connect
        permissions:
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            #- name: Setup Python
            #    uses: actions/setup-python@v2
            #    with:
            #        python-version: 3.8
            #- name: Install virtual env
            #    run:  make .venv
            #- name: Check formatting
            - name: Setup Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install poetry
              uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: "1.5.1"

            - name: poetry build
              run: poetry build
              shell: bash
              
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1