
name: Publish package to PyPI

on:
    push:
        branches:
        - main
    release:
        types:
        - created

jobs:
    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/ocean-sparkconnect
        permissions:
            id-token: write
        steps:
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1